src/components/aeButton/aeButton.scss

```
<ae-button @click='close' size='small' type='plain'>
<ae-icon slot='icon' name='close'/>
</ae-button>
```

aeButton type:plain has no box-shadow

---

README.md

Please discuss and expand/correct this guidelines.

update `new components submission guidelines` first draft

---

src/components/aeButton/aeButton.js
src/components/aeButton/aeButton.md
src/components/aeButton/aeButton.scss
src/components/aeModalLight/aeModalLight.md
src/components/aeModalLight/aeModalLight.vue
src/components/aeModalLight/index.js
src/index.js

https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/screen/5a27ffe4f9a38cac5e8ed165
I decided to implement it as a separate component because otherwise, code of AeModal becomes too complicated. Maybe will be better to remove fullscreen-on-mobile functionality of AeModal, but this functionality has a quite successfully usage in the Response app.
#16

Add AeModalLight component

---

src/components/aeLabel/aeLabel.vue

AeLabel: Allow help text to be multiline

---

src/components/aeIdentity/aeIdentity.scss

fixes image being squashed when right header is added.

fix squash image when right header is added

---

src/components/aeButton/aeButton.js
src/components/aeLabel/aeLabel.vue
src/components/variables.scss
src/constants/index.js

This version of #56 
- supports all types ('boring', 'normal', 'exciting', 'dramatic')
- makes 'normal' the default type (which it implicitly already was)
- follows our CSS modifier class name convention

AeLabel help-type supporst all types (change suggestion to #56)

---

src/components/aeIdentity/aeIdentity.js

[Vue warn]: Invalid default value for prop "identity": Props with type Object/Array must use a factory function to return the default value.
found in
---> &lt;AeIdentity&gt;

AeIdentity: Fix default value of 'identity' prop

---

src/components/aeAppIcon/aeAppIcon.js
src/components/aeAppIcon/aeAppIcon.test.js
src/components/aeAppIcon/aeAppIcon.vue
src/components/aeButton/aeButton.test.js
src/components/aeButton/aeButton.vue
src/mixins/helper.js

Recently I wanted to use the `@click.prevent` modified event on a AeButton. Which did not work, because currently AeButton does not  forward the dispatched native event.
In this PR I made the click event for AeButton and AeAppIcon modifiable.

Improvements in vue event modifiers

---

src/components/aeAddress/aeAddress.js
src/components/aeAddress/aeAddress.md

Extended the validation regex to accept addresses with a length of 97 characters and starting with ak$ or ok$.

Fix issue #69/AeAddress: Accept ak$ and ok$ addresses

---

src/components/aeModal/aeModal.vue

Removes the horizontal scrollbar when width is between 480px and 500px.

AeModal: Avoid horizontal scroll bar

---

src/components/aeIdentity/aeIdentity.js
src/components/aeIdentity/aeIdentity.scss
src/components/aeIdentity/aeIdentity.vue

Perhaps `this.$slots.default` is not a reactive variable since `hasSlot` contains an old value of `$slots.default` after its update.
@Philip-Nunoo is there any reason to enable `transition` for the root node and all children?

AeIdentity fixes

---

src/components/aeAmountInput/aeAmountInput.md
src/components/aeAmountInput/aeAmountInput.vue

Make possible to connect AeAmountInput with AeLabel by "id"/"for" properties.

AeAmountInput: Pass "id" property to child input

---

src/index.js

There's an issue when importing all of the components into a Vue app, the Vue.use doesn't have the Vue object context, and throws an error.
Fixed it by binding the Vue context to the Vue.use function.

Binding Vue context in Vue.use, on all component export

---

__mocks__/@download/blockies.js
package-lock.json
package.json
src/components/aeIdentityAvatar/aeIdentityAvatar.js

Actually, `ethereum-blockies@0.1.1` is broken because of lack of [this change](https://github.com/ethereum/blockies/commit/6eefa4521212216fba9f85feb7570b3ba543e238).  Yesterday it was merged into the upstream repository, it's owner has published a new version. But I still have some problems using this package, I have [made a PR](https://github.com/download13/blockies/pull/11) and waiting for a new version.

Fix ethereum blockies

---

src/components/aeAddress/aeAddress.js

Fixes `Invalid prop: custom validator check failed for prop "address"` exception in Blockchain explorer.

AeAddress: Drop address validation

---

config/global.requires.js
config/webpack.config.js
src/base/variables/_paths.scss
src/components/ae-button/ae-button.js
src/components/ae-input/ae-input.js
src/components/aeAppIcon/aeAppIcon.js
src/components/aeButton/aeButton.js
src/components/aeHeader/aeHeader.vue
src/components/aeIcon/aeIcon.js
src/components/aeIdentity/aeIdentity.js
src/components/aeIdentityBackground/aeIdentityBackground.js
src/components/aeIdentityLight/aeIdentityLight.js
src/components/aeLabel/aeLabel.vue
src/index.js

In addition to arguments in [the similar PR](https://github.com/aeternity/aepp-identity/pull/142) I would like to add that custom aliases makes mode difficult to build components package as a dependency of another project, when it is imported by `@aeternity/aepp-components/src`.
To build components package from the source code can be useful, for example, to enable tree shaking.

Drop webpack aliases

---

config/global.requires.js
src/components/ae-flip/ae-flip.vue
src/components/ae-flip/index.js

Explicit imports of `vue-touch` in components that actually use it make possible to tree-shake this dependency in case if these components are not used in a specific project.

Import `vue-touch` explicitly

---

src/components/ae-drop/index.js
src/components/ae-dropdown/ae-dropdown.md
src/components/ae-dropdown/ae-dropdown.test.js
src/components/ae-dropdown/ae-dropdown.vue
src/components/ae-dropdown/index.js
src/components/index.js

@davidyuk pointed out in one of the comments that `ae-drop` might be confusing so I've renamed the plugin to `ae-dropdown`

renaming ae-drop to ae-dropdown

---

config/styleguidist.config.js

I don't understand why documentation is built only for new components. We have a lot of applications that depend on hidden components. We have to check their state and be sure that they are not broken by the latest changes.

Build documentation for all components, except ones with the same name

---

src/components/ae-check/ae-check.md
src/components/ae-check/ae-check.vue

Expected to be used with AeListItem from #152 like in [Network settings screen](https://github.com/aeternity/aepp-identity/blob/c8232aedc92b011625ff28d5cac7f08d5eec262f/src/pages/SettingsNetwork.vue#L9-L19) of the Base app.
Restored `<input type="checkbox" />` behavior in Vue like in [this examples](https://vuejs.org/v2/guide/forms.html#Checkbox), according to [this guide](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model).
Some changes based on [AeRadio](https://github.com/aeternity/aepp-identity/blob/5c787f1/src/components/AeRadio.vue) component from the Base app.

Refactor AeCheck
