__mocks__/fileMock.js
package.json
src/assets/icons/index.js
src/components/aeIcon/aeIcon.js

As an alternative to #17
https://facebook.github.io/jest/docs/en/webpack.html#handling-static-assets

Fix Jest tests

---

build/webpack.conf.js
package.json
src/components/aeMain/aeMain.md
src/components/aeMain/aeMain.vue
src/components/common.scss
styleguide.config.js

https://github.com/aeternity/aepp-components/pull/15#issuecomment-352044979

Fix styles of examples in styleguidist

---

src/components/aeButton/aeButton.js
src/components/aeButton/aeButton.md
src/components/aeButton/aeButton.scss

AeButton: Add `plain` property

---

src/components/aeButton/aeButton.js

AeButton: Register missed AeLink component

---

src/components/aeDivider/aeDivider.js
src/components/aeDivider/aeDivider.md
src/components/aeDivider/aeDivider.scss
src/components/aeDivider/aeDivider.vue
src/components/aeDivider/index.js
src/index.js

This component is used in the new ae-identity card.

add aeDivider component

---

src/components/aeInput/aeInput.md
src/components/aeInput/aeInput.vue
src/components/aeInput/index.js
src/components/common.scss
src/index.js

Add AeInput component

---

src/components/aeHeader/aeHeader.vue

AeHeader: Fix title alignment

---

src/components/aeBanner/aeBanner.scss

AeBanner: Remove duplicate `padding` property

---

src/components/aeHeader/aeHeader.vue

https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/screen/5a6f47631fa55a1da134c980

Update the backgroud color for AeHeader

---

src/components/aeAmountInput/aeAmountInput.md
src/components/aeAmountInput/aeAmountInput.vue

AeAmountInput: Rename "tokens" prop to "units"

---

src/components/aeLabelledTextInput/aeLabelledTextInput.test.js
src/index.js

Export AeLabelledTextInput, fixes #55

Fix AeLabelledTextInput not being exported

---

package.json

It makes able to install this package by
```
npm i --save git+https://github.com/aeternity/aepp-components.git#testing-changes-davidyuk
```

Extract 'npm run build' to 'prepare' script

---

src/components/aeButton/aeButton.js
src/components/aeLabel/aeLabel.md
src/components/aeLabel/aeLabel.vue
src/components/variables.scss
src/constants/index.js

AeLabel: Make "help-type" the same as "type" of "AeButton"

---

src/components/aeAmountInput/aeAmountInput.test.js
src/components/aeAmountInput/aeAmountInput.vue

- this PR resolve issue #74 and issue #75

Hide chevron if only one unit is passed

---

src/components/aeAccountBackground/aeAccountBackground.js
src/components/aeAccountBackground/aeAccountBackground.md
src/components/aeAccountBackground/aeAccountBackground.scss
src/components/aeAccountBackground/aeAccountBackground.vue
src/components/aeAccountBackground/index.js
src/components/aeIdentity/aeIdentity.scss
src/components/variables.scss
src/constants/index.js
src/index.js

[![Screenshot-2018-3-26_Aeternity_Aepp_Components_Style_Guide_1.png](https://s17.postimg.org/xxwdew4v3/Screenshot-2018-3-26_Aeternity_Aepp_Components_Style_Guide_1.png)](https://postimg.org/image/p2vj4dg2j/)

aeAccountBackground: A component as background for identity related elements

---

src/components/aeAddress/aeAddress.js
src/components/aeAddress/aeAddress.scss
src/components/aeAddress/aeAddress.vue

[![Screenshot-2018-4-6_Aeternity_Aepp_Components_Style_Guide_3.png](https://s31.postimg.org/plbegwekr/Screenshot-2018-4-6_Aeternity_Aepp_Components_Style_Guide_3.png)](https://postimg.org/image/5qpcurzd3/)

ae-address redesign: Styling corrections

---

src/components/aeAmount/aeAmount.md
src/components/aeAmount/aeAmount.scss
src/components/aeAmount/aeAmount.vue

Related to https://github.com/aeternity/aepp-identity/issues/93 and https://github.com/aeternity/aepp-identity/pull/95

Fix ae amount

---

src/components/aeAddress/aeAddress.js
src/components/aeAddress/aeAddress.md
src/components/aeAddress/aeAddress.scss
src/components/aeAddress/aeAddress.test.js
src/components/aeAddress/aeAddress.vue
src/components/aeIcon/aeIcon.vue

- change design of aeAdddress component
- add addition unit tests

ae-address redesign

---

.eslintrc.js
src/components/aeAddress/aeAddress.vue
src/components/aeAddressInput/aeAddressInput.test.js
src/components/aeAddressInput/aeAddressInput.vue
src/components/aeAmountInput/aeAmountInput.vue
src/components/aeBadge/aeBadge.vue
src/components/aeFilterItem/aeFilterItem.vue
src/components/aeFilterList/aeFilterList.vue
src/components/aeFilterSeparator/aeFilterSeparator.vue
src/components/aeHeader/aeHeader.vue
src/components/aeIdentity/aeIdentity.vue
src/components/aeInput/aeInput.vue
src/components/aeLabel/aeLabel.vue
src/components/aeLink/aeLink.vue
src/components/aeLoader/aeLoader.vue
src/components/aeMain/aeMain.vue
src/components/aeOverlay/aeOverlay.vue
src/components/aePanel/aePanel.vue
src/components/aeSwitch/aeSwitch.vue
src/components/aeTextarea/aeTextarea.vue

Please, read this code by commits, I tried to make them very understandable.

Enable more strict eslint vue rules

---

src/components/aeAmountInput/aeAmountInput.vue

Don't perform the default `submit` action

AeAmountInput: Set toggle button type to "button"

---

src/components/aeHeader/aeHeader.vue
src/components/aeModal/aeModal.vue

"AeHeader: Center title without z-index" commit is based on this answer: https://stackoverflow.com/a/33856609

Improvements for Voting app

---

package-lock.json
package.json

With new `vue-styleguidist` package documentation builds faster.

Update "vue-styleguidist" package

---

config/webpack.config.js

Adding `@download/blockies` as an external package.

adding @download/blockies as an external package

---

src/components/ae-backdrop/ae-backdrop.js
src/components/ae-backdrop/ae-backdrop.md
src/components/ae-backdrop/ae-backdrop.scss
src/components/ae-backdrop/ae-backdrop.vue

https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components

AeBackdrop: Use v-if/v-show instead of visible property

---

.eslintignore
.gitignore
config/webpack.bundle.js
config/webpack.components.js
package.json

@sqevani why you have changed the folder for built files from `dist` to `build`? Most of our projects use `dist`.

Build to dist folder

---

src/components/ae-backdrop/ae-backdrop.md
src/components/ae-backdrop/ae-backdrop.vue
src/components/ae-button/ae-button.md
src/components/ae-button/ae-button.vue
src/components/ae-card/ae-card.md
src/components/ae-card/ae-card.vue
src/components/ae-check/ae-check.vue
src/components/ae-flip/ae-flip.md
src/components/ae-flip/ae-flip.vue
src/components/ae-icon/ae-icon.md
src/components/ae-icon/ae-icon.vue
src/components/ae-list-item/ae-list-item.vue
src/components/ae-text/ae-text.vue
src/components/ae-toolbar/ae-toolbar.md
src/components/ae-toolbar/ae-toolbar.vue
src/styles/variables/colors.scss

@davidyuk based on your request the color names have been updated so they don't conflict with internal stuff.

changing color names

---

src/components/ae-address/index.js
src/components/ae-avatar/index.js
src/components/ae-backdrop/index.js
src/components/ae-badge/index.js
src/components/ae-button/index.js
src/components/ae-card/index.js
src/components/ae-check/index.js
src/components/ae-dropdown/index.js
src/components/ae-flip/index.js
src/components/ae-icon/index.js
src/components/ae-input/index.js
src/components/ae-list-item/index.js
src/components/ae-list/index.js
src/components/ae-phraser/index.js
src/components/ae-qrcode/index.js
src/components/ae-text/index.js
src/components/ae-toolbar/index.js
src/components/ae-view/index.js
src/components/index.js

Fixing ` warning  Unexpected unnamed function  func-names`

fixing lint issue

---

src/components/aeIcon/aeIcon.vue

temp fix for the styles going outside the component and affecting other components.

fixing issue where the styles leak outside the component

---

src/components/ae-address/ae-address.vue
src/components/ae-avatar/ae-avatar.vue
src/components/ae-backdrop/ae-backdrop.vue
src/components/ae-badge/ae-badge.vue
src/components/ae-button/ae-button.vue
src/components/ae-card/ae-card.vue
src/components/ae-check/ae-check.vue
src/components/ae-dropdown/ae-dropdown.vue
src/components/ae-flip/ae-flip.vue
src/components/ae-icon/ae-icon.vue
src/components/ae-input/ae-input.vue
src/components/ae-list-item/ae-list-item.vue
src/components/ae-list/ae-list.vue
src/components/ae-phraser/ae-phraser.vue
src/components/ae-qrcode/ae-qrcode.vue
src/components/ae-text/ae-text.vue
src/components/ae-toolbar/ae-toolbar.vue
src/components/ae-view/ae-view.vue

Based on this request: https://github.com/aeternity/aepp-components/pull/178#discussion_r223784109

reformatted styles in new components

---

src/components/ae-button-group/ae-button-group.md
src/components/ae-button-group/ae-button-group.vue

With the same functionality as in #133, the code is simpler and consistent with already written stuff.

Add AeButtonGroup component

---

src/components/ae-backdrop/ae-backdrop.md
src/components/ae-card/ae-card.md
src/components/ae-flip/ae-flip.md
src/components/ae-input-plain/ae-input-plain.md
src/components/ae-input-plain/ae-input-plain.vue
src/components/ae-text/ae-text.md
src/components/ae-text/ae-text.vue
src/components/index.js
src/styles/placeholders/typography.scss

Use this component instead of ae-text in contenteditable mode.

Add AePlainInput component
